[template]
name = "godot-tag-game"

[variables.project_name]
type = "string"
prompt = "Project name"
default = "my-tag-game"
validation = '^[a-zA-Z][a-zA-Z0-9_-]*$'
validation_message = "Must start with a letter, alphanumeric/hyphens/underscores only"

[variables.author]
type = "string"
prompt = "Author name"
default = "Your Name"

[variables.description]
type = "string"
prompt = "Project description"
default = "A multiplayer tag game built with Godot"

[variables.godot_version]
type = "string"
prompt = "Godot version"
default = "4.3"

[files]
exclude = [
    ".git/**",
    ".godot/**",
    "*.import",
    ".gitattributes"
]
copy_without_render = [
    "**/*.png",
    "**/*.svg"
]

[hooks]
post_create = "echo 'Template created! Open project.godot in Godot Editor to start developing.'"
